2024-04-23 19:30:29,250 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -5343755394470609618

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:30:42,397 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -5343755394470609618

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:36:22,724 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:36:24,419 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:36:25,326 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:36:25,977 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:36:35,703 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:37:03,537 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-23 19:37:03,647 ERROR frappe Failed to run after request hook
Site: done_with.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 3730527124323547725

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 127, in application
    run_after_request_hooks(request, response)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/app.py", line 143, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1506, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1469, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/__init__.py", line 1425, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/lucky/tut-bench-two/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lucky/tut-bench-two/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'lucky'@'localhost' (using password: NO)")
2024-04-24 06:03:04,475 ERROR frappe New Exception collected with id: 2024-04-24 06:03:04.325118-127.0.0.1-0e5
Site: done_with.com
Form Dict: {'doctype': 'Listing', 'with_parent': '1', 'cached_timestamp': '2024-04-23 23:20:16.362700', 'cmd': 'frappe.desk.form.load.getdoctype'}
2024-04-24 21:16:49,900 ERROR frappe New Exception collected with id: 2024-04-24 21:16:49.767789-127.0.0.1-828
Site: done_with.com
Form Dict: {'doc': '{"name":"Tv-05","owner":"Administrator","creation":"2024-04-23 23:21:17.667007","modified":"2024-04-24 11:54:38.320085","modified_by":"yelnatstech@gmail.com","docstatus":0,"idx":0,"item_name":"Tv","acquired_on":"2024-04-10","route":"Tv-05","price":100,"image":"https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=600","is_published":1,"totals":"80","description":"A vintage Tv","doctype":"Listing","shown_interest":[{"docstatus":0,"doctype":"Listing Request","name":"new-listing-request-rymyrmxqxz","__islocal":1,"__unsaved":1,"owner":"yelnatstech@gmail.com","parent":"Tv-05","parentfield":"shown_interest","parenttype":"Listing","idx":1,"__unedited":false,"full_name":"hellen","mobile_number":"5554445","price_offered":"550"}],"__onload":{"is_website_generator":true,"published":true},"__last_sync_on":"2024-04-24T18:15:09.203Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
